# In order to build for staging run:
# $ jekyll build --config _config.yml, _config-staging.yml
#
#
# URL of static site
url: "https://www.op-tee.org"
# Destination folder
destination: production.op-tee.org
# Production boolean used in layouts / includes
production: true